version: '3.8'

services:
    sftp:
      image: atmoz/sftp:alpine
      container_name: sftp
      volumes:
          - ./tests/fixtures:/home/extract/upload
      ports:
          - "22:22"
      command: extract:password:1001

    database:
        image: postgres:latest
        restart: always
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
        ports:
        - '5432:5432'
        volumes: 
            - ./database_setup:/docker-entrypoint-initdb.d
