name: CI
on: [push]
jobs:
    docker-compose:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Start containers
          run: docker-compose -f "docker-compose.yml" up -d
    
    tox:
        runs-on: ubuntu-latest
        needs: docker-compose
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Install tox
          run: pip install tox

        - name: Run tox
          run: tox -e test

    stop-containers:
        runs-on: ubuntu-latest
        if: always()
        steps:
        - name: Stop containers
          run: |
                docker-compose -f "docker-compose.yml" down
                docker-compose -f "docker-compose.yml" down -v
